### Wine API - GET 요청 (Wine 리스트 조회)
GET https://winereview-api.vercel.app/10-2/wines?limit=5 HTTP/1.1
Content-Type: application/json

###

POST https://winereview-api.vercel.app/10-4/auth/signUp
Content-Type: application/json

  {
     "email": "test11-5@whyne.com",
     "nickname": "testAccount",
     "password": "12341234",
     "passwordConfirmation": "12341234"
   }

# POST https://winereview-api.vercel.app/10-4/auth/signIn
# Content-Type: application/json

#   {
#      "email": "test11-5@whyne.com",
#      "password": "12341234"
#    }